logging:
  level: DEBUG
  loggers:
    io.dropwizard: INFO
    org.eclipse: ERROR
  appenders:
    - type: console
server:
  applicationConnectors:
    - type: http
      port: 9020
  adminConnectors:
    - type: http
      port: 9021
email:
  host: email-smtp.us-west-2.amazonaws.com
  port: 587
  tls: true
#  emailTo: harry.common.uk@gmail.com
#  emailFrom: harry.common.uk@gmail.com
#  user: AKIAI7ZHYASLHRJWJYOQ
#  password: Aivm8yLM4I31b+Iq5s2BZB3CeoIFAMpRFNE6s7MR1pcb
  emailTo: hkjtest@gmail.com
  emailFrom: hkjtest@gmail.com
  user: AKIAIXIKELZAJXERTANQ
  password: Aq0DdA7svkwx9ufu8oE1U/S5bNXExJ9RFmkQ/yZykrHc
  bodyMessage: Data Returns Import file received
