logging:
  level: ERROR
  loggers:
    uk.gov.ea.datareturns: DEBUG
    io.dropwizard: INFO
    org.eclipse: ERROR
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  fileUploadLocation: ./uploaded
  schemaFileLocation: ./schemas
email:
  host: email-smtp.us-west-2.amazonaws.com
  port: 587
  tls: true
  emailTo: hkjtest@gmail.com
  emailFrom: hkjtest@gmail.com
  user: AKIAIXIKELZAJXERTANQ
  password: Aq0DdA7svkwx9ufu8oE1U/S5bNXExJ9RFmkQ/yZykrHc
  bodyMessage: Data Returns Import file received
database:
  url: jdbc:postgresql://localhost:5432/data_returns
  driverClass: org.postgresql.Driver
  user: data_returns_owner
  password: data_returns_owner
