logging:
  level: ERROR
  loggers:
    uk.gov.ea.datareturns: DEBUG
    com.healthmarketscience: DEBUG
    io.dropwizard: INFO
    org.eclipse: ERROR
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  fileUploadLocation: ./uploaded
  schemaFileLocation: ./schemas
email:
  host: 127.0.0.1
  port: 1025
  emailTo: import@monitorpro.com
  emailFrom: data_returns@environment-agency.gov.uk
  tls: false
  bodyMessage: Data Returns Import file received
database:
  driverClass: com.p6spy.engine.spy.P6SpyDriver
  url: jdbc:p6spy:postgresql://localhost:5432/data_returns
  #url: jdbc:postgresql://localhost:5432/data_returns
  #driverClass: org.postgresql.Driver
  user: data_returns_owner
  password: data_returns_owner
