logging:
  level: DEBUG
  loggers:
    io.dropwizard: INFO
    org.eclipse: ERROR
  appenders:
    - type: console
server:
    applicationConnectors:
        - type: http
          port: 9020
email:
  host: 127.0.0.1
  port: 1025
  emailTo: import@monitorpro.com
  emailFrom: data_returns@environment-agency.gov.uk
  tls: false
  bodyMessage: Data Returns Import file received