logging:
  level: ERROR
  loggers:
    uk.gov.ea.datareturns: DEBUG
    io.dropwizard: INFO
    org.glassfish: ERROR
    org.eclipse: ERROR
    # Useful to log REST requests and responses 
    org.glassfish.jersey.filter: DEBUG
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  environment: local
  uploadedLocation: ./external_resources/uploaded
  outputLocation: ./external_resources/output
  schemaLocation: ./external_resources/schema
  xsltLocation: ./external_resources/xslt
  xmlLocation: ./external_resources/xml
  csvSeparator: ","
  debugMode: true
# LIVE SETTINGS FOR THE EMMA DATABASE - DO NOT USE FOR TEST PURPOSES!
#emmaDatabase:
#  databaseLowerNumericName: EA_LP_10000_TO_69000_LIST
#  databaseUpperNumericName: EA_LP_70000_ABOVE_LIST
#  databaseLowerAlphaNumericName: EA_LP_AA_TO_GZ_LIST
#  databaseUpperAlphaNumericName: EA_LP_HA_TO_ZZ_LIST
emmaDatabase:
  databaseLowerNumericName: EA_TEST_ENVIRONMENT
  databaseUpperNumericName: EA_TEST_ENVIRONMENT
  databaseLowerAlphaNumericName: EA_TEST_ENVIRONMENT
  databaseUpperAlphaNumericName: EA_TEST_ENVIRONMENT
test:
  testFilesLocation: /testfiles
  testTimeout: 1000000
  cleanupAfterTestRun: false
