logging:
  level: INFO
  loggers:
    uk.gov.ea.datareturns: DEBUG
    io.dropwizard: INFO
    org.glassfish: ERROR
    org.eclipse: ERROR
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  environment: test
  uploadedLocation: ./external_resources/uploaded
  outputLocation: ./external_resources/output
  schemaLocation: ./external_resources/schema
  xsltLocation: ./external_resources/xslt
  xmlLocation: ./external_resources/xml
  csvSeparator: ","
  debugMode: false
test:
  testFilesLocation: /testfiles
  testTimeout: 10000
  cleanupAfterTestRun: true
