logging:
  level: INFO
  loggers:
    uk.gov.ea.datareturns: DEBUG
    io.dropwizard: INFO
    org.glassfish: ERROR
    org.eclipse: ERROR
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  uploadedLocation: ./uploaded
  outputLocation: ./output
  schemaLocation: ./external_resources/schema
  xsltLocation: ./external_resources/xslt
  xmlLocation: ./external_resources/xml
  testFilesLocation: /testfiles
  defaultTestTimeout: 10000
  debugTestTimeout : 10000
  debugMode: false
  cleanupAfterTestRun: true
email:
  host: 127.0.0.1
  port: 1025
  emailTo: import@monitorpro.com
  emailFrom: data_returns@environment-agency.gov.uk
  tls: false
  bodyMessage: Data Returns Import file received
database:
  url: jdbc:postgresql://data-returns.cn1r9x2itg1r.eu-west-1.rds.amazonaws.com:5432/data_returns
  driverClass: org.postgresql.Driver
  user: data_returns_owner
  password: data_returns_owner
