logging:
  level: INFO
  loggers:
    uk.gov.ea.datareturns: DEBUG
    io.dropwizard: INFO
    org.glassfish: ERROR
    org.eclipse: ERROR
  appenders:
  - type: console
  - type: file
    currentLogFilename: log/datareturns.log
    archivedLogFilenamePattern: log/datareturns-%d.log
    threshold: ALL
    archive: true
    archivedFileCount: 5
    timeZone: UTC
server:
  applicationConnectors:
  - type: http
    port: 9020
  adminConnectors:
  - type: http
    port: 9021
misc:
  uploadedLocation: ./external_resources/uploaded
  outputLocation: ./external_resources/output
  schemaLocation: ./external_resources/schema
  xsltLocation: ./external_resources/xslt
  xmlLocation: ./external_resources/xml
  csvSeparator: ","
  debugMode: false
test:
  testFilesLocation: /testfiles
  testTimeout: 10000
  cleanupAfterTestRun: true
email:
  host: email-smtp.eu-west-1.amazonaws.com
  port: 587
  user: AKIAIXX25ZNDL33YHUIA
  password: AmK/wWewBglYrvpyRmnLCPm7KlEcXJqPHMJIao585bzP
  emailTo: ea.importer@ehsdata.com
  emailFrom: datareturns@envage.co.uk
  tls: true
  bodyMessage: Data Returns Import file received
database:
  url: jdbc:postgresql://data-returns.cn1r9x2itg1r.eu-west-1.rds.amazonaws.com:5432/data_returns
  driverClass: org.postgresql.Driver
  user: data_returns_owner
  password: data_returns_owner
