/**
 * 
 */
package uk.gov.ea.datareturns.domain.model.validation.auditors;

import java.util.HashSet;
import java.util.Set;

import uk.gov.ea.datareturns.domain.model.validation.constraints.controlledlist.ControlledListAuditor;

/**
 * @author sam
 *
 */
public class ParameterListAuditor implements ControlledListAuditor {

	private static final Set<String> PARAMETERS = new HashSet<>();
	static {
        PARAMETERS.add("(2-Methoxymethylethoxy)propanol");
        PARAMETERS.add("1,1,1,2-Tetrachloroethane");
        PARAMETERS.add("1,1,1,2-Tetrafluoroethane");
        PARAMETERS.add("1,1,1-trichloro-2,2-ethane");
        PARAMETERS.add("1,1,1-Trichloroethane");
        PARAMETERS.add("1,1,2,2-Tetrabromoethane");
        PARAMETERS.add("1,1,2,2-Tetrachloroethane");
        PARAMETERS.add("1,1,2-Trichloroethane");
        PARAMETERS.add("1,1,2-Trichloroethene");
        PARAMETERS.add("1,1-dichloro-2,2-bis-ethane");
        PARAMETERS.add("1,1-Dichloroethane");
        PARAMETERS.add("1,1-Dichloroethene");
        PARAMETERS.add("1,1-Dichloroethylene");
        PARAMETERS.add("1,1-Dichloropropene");
        PARAMETERS.add("1,1-Dimethylethylbenzene");
        PARAMETERS.add("1,2,3 Indeno (cd) pyrene");
        PARAMETERS.add("1,2,3,4-Tetrachlorobenzene");
        PARAMETERS.add("1,2,3,4-Tetrachloro-benzene");
        PARAMETERS.add("1,2,3-Trichlorobenzene");
        PARAMETERS.add("1,2,3-Trichloropropane");
        PARAMETERS.add("1,2,3-Trimethylbenzene");
        PARAMETERS.add("1,2,4,5-Tetrachlorobenzene");
        PARAMETERS.add("1,2,4-Trichlorobenzene");
        PARAMETERS.add("1,2,4-Trimethylbenzene");
        PARAMETERS.add("1,2-Dibromo-3-chloropropane");
        PARAMETERS.add("1,2-Dibromoethane");
        PARAMETERS.add("1,2-Dichlorobenzene");
        PARAMETERS.add("1,2-Dichloroethane");
        PARAMETERS.add("1,2-Dichloroethene");
        PARAMETERS.add("1,2-Dichloropropane");
        PARAMETERS.add("1,3,5 Trimethylbenzene");
        PARAMETERS.add("1,3,5-Trichlorobenzene");
        PARAMETERS.add("1,3,5-Trimethylbenzene");
        PARAMETERS.add("1,3,5-Trinitrobenzene");
        PARAMETERS.add("1,3-Butadiene");
        PARAMETERS.add("1,3-Dichloro-5,5-dimethylhydantoin");
        PARAMETERS.add("1,3-Dichlorobenzene");
        PARAMETERS.add("1,3-Dichloropropane");
        PARAMETERS.add("1,3-Dichloropropene");
        PARAMETERS.add("1,3-Dinitrobenzene");
        PARAMETERS.add("1,4-Dichlorobenzene");
        PARAMETERS.add("1,4-Dioxane");
        PARAMETERS.add("1,4-Naphthoquinone");
        PARAMETERS.add("1,6-Hexanolactam");
        PARAMETERS.add("16-(Thienylmethylene)Androstane-3,17-Diol SVOCS");
        PARAMETERS.add("1-Butanethiol");
        PARAMETERS.add("1-Chloro-4-nitrobenzene");
        PARAMETERS.add("1-Hexanol, 2 ethyl- (SVOCSW)");
        PARAMETERS.add("1-Methoxypropan-2-ol");
        PARAMETERS.add("1-Methoxypropyl Acetate");
        PARAMETERS.add("1-Methyl-2-pyrrolidone");
        PARAMETERS.add("1-Methylethylbenzene");
        PARAMETERS.add("1-Methylnaphthalene");
        PARAMETERS.add("1-Methylpropylbenzene");
        PARAMETERS.add("1-Naphthylamine");
        PARAMETERS.add("1-Pentene");
        PARAMETERS.add("1-Propanethiol");
        PARAMETERS.add("2-(2-Butoxyethoxy)ethanol");
        PARAMETERS.add("2-(2-Methoxyethoxy)ethanol");
        PARAMETERS.add("2(3H)-Benzothiazolone");
        PARAMETERS.add("2,2 Dichloropropane + 1,2 Dichloroethylene");
        PARAMETERS.add("2,2'-Dichloro-4,4'-methylenedianiline (MbOCA)");
        PARAMETERS.add("2,2-Dichloropropane");
        PARAMETERS.add("2,2-Dipyridyl");
        PARAMETERS.add("2,2'-Iminodi(ethylamine)");
        PARAMETERS.add("2,2'-Oxydiethanol");
        PARAMETERS.add("2,3,4,6-Tetrachlorophenol");
        PARAMETERS.add("2,3,4-Trimethylphenol");
        PARAMETERS.add("2,3,5-Trimethylphenol");
        PARAMETERS.add("2,3,6-TBA");
        PARAMETERS.add("2,3,6-Trimethylphenol");
        PARAMETERS.add("2,3-Dichlorophenol");
        PARAMETERS.add("2,3-Dimethylphenol");
        PARAMETERS.add("2,4,5-T");
        PARAMETERS.add("2,4,5-T (2,4,5-Trichlorophenoxyacetic Acid)");
        PARAMETERS.add("2,4,5-Trichlorophenol");
        PARAMETERS.add("2,4,6-Tribromophenol");
        PARAMETERS.add("2,4,6-Trichlorophenol");
        PARAMETERS.add("2,4,6-Trichlorophenol STLGG4");
        PARAMETERS.add("2,4,6-Trichlorophenol STLPK2");
        PARAMETERS.add("2,4,6-Trimethyl phenol");
        PARAMETERS.add("2,4,6-Trinitrotoluene");
        PARAMETERS.add("2,4-D");
        PARAMETERS.add("2,4-D ((2,4-Dichlorophenoxy)acetic Acid)");
        PARAMETERS.add("2,4-DB (4-(2,4-DichFlorophenoxy)butyric Acid)");
        PARAMETERS.add("2,4-DDD");
        PARAMETERS.add("2,4-DDE");
        PARAMETERS.add("2,4-DDT");
        PARAMETERS.add("2,4-Dichlorophenol");
        PARAMETERS.add("2,4-dichlorophenoxy acetic acid");
        PARAMETERS.add("2,4-Dimethylphenol");
        PARAMETERS.add("2,4-Dinitrophenol");
        PARAMETERS.add("2,4-Dinitrotoluene");
        PARAMETERS.add("2,4-imethylphenol low level");
        PARAMETERS.add("2,5-Dichlorophenol");
        PARAMETERS.add("2,5-Dimethylphenol");
        PARAMETERS.add("2,6-Dichlorophenol");
        PARAMETERS.add("2,6-Dimethylheptan-4-one");
        PARAMETERS.add("2,6-Dimethylphenol");
        PARAMETERS.add("2,6-Dinitrotoluene");
        PARAMETERS.add("2,6-Di-tert-butyl-p-cresol");
        PARAMETERS.add("2-Acetylaminofluorene");
        PARAMETERS.add("2-Aminoethanol");
        PARAMETERS.add("2-Butoxy ethanol");
        PARAMETERS.add("2-Butoxyethanol");
        PARAMETERS.add("2-Butoxyethyl Acetate");
        PARAMETERS.add("2-Chloroacetophenone");
        PARAMETERS.add("2-Chloroaniline");
        PARAMETERS.add("2-Chloroethanol");
        PARAMETERS.add("2-Chloronaphthalene");
        PARAMETERS.add("2-Chlorophenol");
        PARAMETERS.add("2-Chlorotoluene");
        PARAMETERS.add("2-Dimethylaminoethanol");
        PARAMETERS.add("2-Ethoxyethanol");
        PARAMETERS.add("2-Ethoxyethyl Acetate");
        PARAMETERS.add("2-Ethylhexyl Chloroformate");
        PARAMETERS.add("2-Fluorobiphenyl");
        PARAMETERS.add("2-Fluorophenol");
        PARAMETERS.add("2-Furaldehyde (Furfural)");
        PARAMETERS.add("2-Hydroxypropyl Acrylate");
        PARAMETERS.add("2-Methoxyethanol");
        PARAMETERS.add("2-Methoxyethyl Acetate");
        PARAMETERS.add("2-Methyl Naphthalene");
        PARAMETERS.add("2-Methyl-2-propanol");
        PARAMETERS.add("2-Methyl-4,6-dinitrophenol");
        PARAMETERS.add("2-Methylcyclohexanone");
        PARAMETERS.add("2-Methylnaphthalene");
        PARAMETERS.add("2-Methylpentane-2,4-diol");
        PARAMETERS.add("2-Methylphenol");
        PARAMETERS.add("2-Methylpropan-1-ol");
        PARAMETERS.add("2-Methylpropan-2-ol");
        PARAMETERS.add("2-Naphthylamine");
        PARAMETERS.add("2-Nitroaniline");
        PARAMETERS.add("2-Nitrophenol");
        PARAMETERS.add("2-Nitropropane");
        PARAMETERS.add("2-Phenylpropene");
        PARAMETERS.add("2-Picoline");
        PARAMETERS.add("2-Pyridylamine");
        PARAMETERS.add("2-sec-Butylphenol");
        PARAMETERS.add("3 and 4-Chlorophenol");
        PARAMETERS.add("3 and 4-Methylphenol");
        PARAMETERS.add("3 x Volume");
        PARAMETERS.add("3,3-Dichlorobenzidine");
        PARAMETERS.add("3,3-Dimethylbenzidine");
        PARAMETERS.add("3,3-Dimethylheptanoic acid");
        PARAMETERS.add("3,4-Dichlorophenol");
        PARAMETERS.add("3,4-Dihydrobenzo[c]pyran-1 [2H]-ol [SVOCSW]");
        PARAMETERS.add("3,4-Dimethylphenol");
        PARAMETERS.add("3,5,5-Trimethylcyclohex-2-enone");
        PARAMETERS.add("3,5-Dimethylphenol");
        PARAMETERS.add("3,5-di-tert-Buyl-4-hydroxyphenylpropionic acid [S]");
        PARAMETERS.add("3,6,6-Trimethylnorpinan-2-one[SVOCSW]");
        PARAMETERS.add("3-Chloroaniline");
        PARAMETERS.add("3-Chlorophenol");
        PARAMETERS.add("3-Cyclohexene-1-methanol, .alpha.,.alpha.4- tri");
        PARAMETERS.add("3-Methyl-6-hydroxybenzo[c]-dihydrofuran[SVOCSW]");
        PARAMETERS.add("3-Methylbutan-1-ol");
        PARAMETERS.add("3-Methylcholanthrene");
        PARAMETERS.add("3-Methylphenol");
        PARAMETERS.add("3-Nitroaniline");
        PARAMETERS.add("4,4'-DDD");
        PARAMETERS.add("4,4'-DDE");
        PARAMETERS.add("4,4'-DDT");
        PARAMETERS.add("4,4-Dipyridyl");
        PARAMETERS.add("4,4'-Methylenedianiline (MDA)");
        PARAMETERS.add("4,6-Dinitro-2-methylphenol");
        PARAMETERS.add("4-Aminobiphenyl");
        PARAMETERS.add("4-Bromofluorobenzene");
        PARAMETERS.add("4-Bromophenyl phenyl ether");
        PARAMETERS.add("4-Chloro-3-methylphenol");
        PARAMETERS.add("4-Chloroacetophenone");
        PARAMETERS.add("4-Chloroaniline");
        PARAMETERS.add("4-chloro-o-tolyloxyacetic acid");
        PARAMETERS.add("4-Chlorophenol");
        PARAMETERS.add("4-Chlorophenyl phenylether");
        PARAMETERS.add("4-Chlorotoluene");
        PARAMETERS.add("4-Ethylmorpholine");
        PARAMETERS.add("4-Ethylphenol");
        PARAMETERS.add("4-Hydroxy-4-methylpentan-2-one");
        PARAMETERS.add("4-Isopropyltoluene");
        PARAMETERS.add("4-Methyl-2-pentanone");
        PARAMETERS.add("4-Methylpentan-2-ol");
        PARAMETERS.add("4-Methylpentan-2-one");
        PARAMETERS.add("4-Methylphenol");
        PARAMETERS.add("4-Methylphenol STLGHP");
        PARAMETERS.add("4-Methylphenol STLPJK");
        PARAMETERS.add("4-Nitroaniline");
        PARAMETERS.add("4-Nitrophenol");
        PARAMETERS.add("5-Cyclopropyl-3-nitropyrazole[SVOCSW]");
        PARAMETERS.add("5-Methylheptan-3-one");
        PARAMETERS.add("5-Methylhexan-2-one");
        PARAMETERS.add("6,6'-Di-tert-butyl-4,4'-thiodi-m-cresol");
        PARAMETERS.add("7,12=Dimethylbenz(a)anthracene");
        PARAMETERS.add("9-Ethyl-9-methylfluorene[SVOCSW]");
        PARAMETERS.add("Abamectin");
        PARAMETERS.add("Acenaphthene");
        PARAMETERS.add("Acenaphthylene");
        PARAMETERS.add("Acenaphthylene (PAH)");
        PARAMETERS.add("Acenaphthylene ESG SVOC");
        PARAMETERS.add("Acetaldehyde");
        PARAMETERS.add("Acetic acid");
        PARAMETERS.add("Acetic Anhydride");
        PARAMETERS.add("Acetone");
        PARAMETERS.add("Acetonitrile");
        PARAMETERS.add("Acetophenone");
        PARAMETERS.add("Acetylene");
        PARAMETERS.add("Acrylaldehyde (Acrolein)");
        PARAMETERS.add("Acrylamide");
        PARAMETERS.add("Acrylonitrile");
        PARAMETERS.add("Actioned");
        PARAMETERS.add("Activated Carbon");
        PARAMETERS.add("Adsorbable Organicly bound halogens (AOX)");
        PARAMETERS.add("Alachlor");
        PARAMETERS.add("Aldicarb");
        PARAMETERS.add("Aldrin");
        PARAMETERS.add("Aliphatics &lt;C10-C12");
        PARAMETERS.add("Aliphatics > EC12-EC35 (aq)");
        PARAMETERS.add("Aliphatics >C12-C16 (aq)");
        PARAMETERS.add("Aliphatics >C16-C21 (aq)");
        PARAMETERS.add("Aliphatics >C21-C35 (aq)");
        PARAMETERS.add("Aliphatics >C5-C12");
        PARAMETERS.add("Aliphatics >C5-C6");
        PARAMETERS.add("Aliphatics >C6-C8");
        PARAMETERS.add("Aliphatics >C8-C10");
        PARAMETERS.add("Aliphatics and Aromatics > C5-35 (aq)");
        PARAMETERS.add("Alkalinity (Total)");
        PARAMETERS.add("Alkalinity as CaCO3");
        PARAMETERS.add("Alkalinity as HC03");
        PARAMETERS.add("Allyl Alcohol");
        PARAMETERS.add("Alpha Analysis");
        PARAMETERS.add("Alpha-BHC");
        PARAMETERS.add("alpha-Chlordane");
        PARAMETERS.add("alpha-Chlorotoluene");
        PARAMETERS.add("alpha-Endosulphan");
        PARAMETERS.add("alpha-Methyl Styrene");
        PARAMETERS.add("Aluminium");
        PARAMETERS.add("Aluminium Alkyl Compounds");
        PARAMETERS.add("Aluminium Oxides");
        PARAMETERS.add("Aluminium Salts, Soluble");
        PARAMETERS.add("Aluminium, Dissolved");
        PARAMETERS.add("Ametryn");
        PARAMETERS.add("Ammonia");
        PARAMETERS.add("Ammonia (NH3)");
        PARAMETERS.add("Ammonia as N");
        PARAMETERS.add("Ammoniacal Nitrogen");
        PARAMETERS.add("Ammonium");
        PARAMETERS.add("Ammonium Chloride, Fume");
        PARAMETERS.add("Ammonium Sulphamidate");
        PARAMETERS.add("Anemometer");
        PARAMETERS.add("Aniline");
        PARAMETERS.add("Anions total");
        PARAMETERS.add("Anthracene");
        PARAMETERS.add("Anthracene (PAH)");
        PARAMETERS.add("Anthracene ESG SVOC");
        PARAMETERS.add("Antimony");
        PARAMETERS.add("AOX");
        PARAMETERS.add("APC Residues");
        PARAMETERS.add("Aromatics > EC10-EC12");
        PARAMETERS.add("Aromatics >EC12-EC16 (aq)");
        PARAMETERS.add("Aromatics >EC16-EC21 (aq)");
        PARAMETERS.add("Aromatics >EC21-EC35 (aq)");
        PARAMETERS.add("Aromatics >EC5-EC7");
        PARAMETERS.add("Aromatics >EC7-EC8");
        PARAMETERS.add("Aromatics >EC8-EC10");
        PARAMETERS.add("Aromatics Total > EC12-EC35 (aq)");
        PARAMETERS.add("Arsenic");
        PARAMETERS.add("Arsine");
        PARAMETERS.add("Asbestos");
        PARAMETERS.add("Asbestos Fibres");
        PARAMETERS.add("Asphalt, Petroleum Fumes");
        PARAMETERS.add("Atmospheric Pressure");
        PARAMETERS.add("Atraton");
        PARAMETERS.add("Atrazine");
        PARAMETERS.add("Azamethiphos");
        PARAMETERS.add("Azinphos-ethyl");
        PARAMETERS.add("Azinphos-methyl");
        PARAMETERS.add("Azobenzene");
        PARAMETERS.add("Azodicarbonamide");
        PARAMETERS.add("Azoxystrobin");
        PARAMETERS.add("Balance");
        PARAMETERS.add("Barium");
        PARAMETERS.add("Barium Sulphate");
        PARAMETERS.add("Barometric Pressure");
        PARAMETERS.add("BBP (Butyl Benzyl Phthalate)");
        PARAMETERS.add("Bentazone");
        PARAMETERS.add("Benzatone");
        PARAMETERS.add("Benzene");
        PARAMETERS.add("Benzenebutanoic acid");
        PARAMETERS.add("Benzidine");
        PARAMETERS.add("Benzo 1,12 perylene (ghi)");
        PARAMETERS.add("Benzo 11,12 fluoranthene (k)");
        PARAMETERS.add("Benzo(a)anthracene");
        PARAMETERS.add("Benzo(a)pyrene");
        PARAMETERS.add("Benzo(b)fluoranthene");
        PARAMETERS.add("Benzo(ghi)perylene");
        PARAMETERS.add("Benzo(k)fluoranthene");
        PARAMETERS.add("Benzo[a]pyrene");
        PARAMETERS.add("Benzo[b]fluoranthene");
        PARAMETERS.add("Benzo[g,h,i]perylene");
        PARAMETERS.add("Benzo[k]fluoranthene");
        PARAMETERS.add("Benzoic Acid");
        PARAMETERS.add("Benzothiazolone");
        PARAMETERS.add("Benzyl alcohol");
        PARAMETERS.add("Benzyl butyl phthalate");
        PARAMETERS.add("Benzyl Chloride");
        PARAMETERS.add("Beryllium");
        PARAMETERS.add("Beta Analysis");
        PARAMETERS.add("Bicarbonate");
        PARAMETERS.add("Biochemical oxygen demand (BOD5)");
        PARAMETERS.add("Biocides");
        PARAMETERS.add("Biphenyl");
        PARAMETERS.add("Bis(2-chloroethoxy)methane");
        PARAMETERS.add("Bis(2-chloroethyl) ether");
        PARAMETERS.add("Bis(2-chloroisopropyl) ether");
        PARAMETERS.add("Bis(2-chloroisopropyl)ether");
        PARAMETERS.add("bis(2-ethylhexyl)phthalate");
        PARAMETERS.add("Bis(chloromethyl) Ether");
        PARAMETERS.add("BOD (Biological Oxygen Demand)");
        PARAMETERS.add("Bolstar");
        PARAMETERS.add("Booster Pressure");
        PARAMETERS.add("Booster Suction");
        PARAMETERS.add("Borate");
        PARAMETERS.add("Borehole Base AOD");
        PARAMETERS.add("Borehole Base Below Ref Point");
        PARAMETERS.add("Borehole Base Top of Silt MBRP");
        PARAMETERS.add("Borehole Leachate Depth Above Basal Liner");
        PARAMETERS.add("Borehole Liquid Level AOD");
        PARAMETERS.add("Borehole Liquid Level Below Ref Point");
        PARAMETERS.add("Borehole Metal Casing");
        PARAMETERS.add("Borehole Reference Point Above Site Datum");
        PARAMETERS.add("Borehole Reference Point AOD");
        PARAMETERS.add("Borehole Standing Depth of Liquid");
        PARAMETERS.add("Borehole top of silt");
        PARAMETERS.add("Borehole Volume");
        PARAMETERS.add("Bornan-2-one");
        PARAMETERS.add("Boron");
        PARAMETERS.add("Boron Tribromide");
        PARAMETERS.add("Boscalid");
        PARAMETERS.add("Bottom Ash");
        PARAMETERS.add("Bromacil");
        PARAMETERS.add("Bromate");
        PARAMETERS.add("Bromate as BrO3");
        PARAMETERS.add("Bromide");
        PARAMETERS.add("Bromine");
        PARAMETERS.add("Bromobenzene");
        PARAMETERS.add("Bromochloromethane");
        PARAMETERS.add("Bromodichloromethane");
        PARAMETERS.add("Bromoform");
        PARAMETERS.add("Bromomethane");
        PARAMETERS.add("Bromoxynil");
        PARAMETERS.add("Bromoxynil octanoate");
        PARAMETERS.add("BTEX - Sum of detected");
        PARAMETERS.add("Butan-1-ol");
        PARAMETERS.add("Butan-2-ol");
        PARAMETERS.add("Butan-2-one (Methyl Ethyl Ketone)");
        PARAMETERS.add("Butane");
        PARAMETERS.add("Butanes");
        PARAMETERS.add("Butanoic acid, 2-methyl-[SVOCSW]");
        PARAMETERS.add("Butenes");
        PARAMETERS.add("Butyl Acetate");
        PARAMETERS.add("Butyl Benzenesulphonamide");
        PARAMETERS.add("Butyl Lactate");
        PARAMETERS.add("Butylbenzylphthalate");
        PARAMETERS.add("Butyric Acid");
        PARAMETERS.add("Butyric Acid (4-(2,4-dichlorophenoxy)-Butanoic aci");
        PARAMETERS.add("C10-C13 Chloroalkanes");
        PARAMETERS.add("C7-C9 Dialkyl Phthalates");
        PARAMETERS.add("Cadmium");
        PARAMETERS.add("Cadmium - Total Unfiltered");
        PARAMETERS.add("Cadmium &amp; thallium and their compounds (total)");
        PARAMETERS.add("Cadmium and its compounds, expressed as cadmium (Total Cd)");
        PARAMETERS.add("Cadmium Oxide");
        PARAMETERS.add("Cadmium Sulphide and Cadmium Sulphide Pigments (Respirable Dust) (As Cd)");
        PARAMETERS.add("Caesium Hydroxide");
        PARAMETERS.add("Calcium");
        PARAMETERS.add("Calcium - Total Unfiltered");
        PARAMETERS.add("Calcium Carbonate");
        PARAMETERS.add("Calcium Chloride");
        PARAMETERS.add("Calcium Cyanamide");
        PARAMETERS.add("Calcium Hardness as CaCO3");
        PARAMETERS.add("Calcium Hydroxide");
        PARAMETERS.add("Calcium Oxide");
        PARAMETERS.add("Calcium Silicate");
        PARAMETERS.add("Camphor");
        PARAMETERS.add("Captan");
        PARAMETERS.add("Carbazole");
        PARAMETERS.add("Carbendazim");
        PARAMETERS.add("Carbetamide");
        PARAMETERS.add("Carbofuran");
        PARAMETERS.add("Carbon Black");
        PARAMETERS.add("Carbon Dioxide");
        PARAMETERS.add("Carbon Disulphide");
        PARAMETERS.add("Carbon Monoxide");
        PARAMETERS.add("Carbon monoxide (CO)");
        PARAMETERS.add("Carbonate");
        PARAMETERS.add("Carbontetrachloride");
        PARAMETERS.add("Carbonyl Sulphide");
        PARAMETERS.add("Carbophenothion");
        PARAMETERS.add("Cations total");
        PARAMETERS.add("Cellulose");
        PARAMETERS.add("CH4");
        PARAMETERS.add("Chemical oxygen demand (COD)");
        PARAMETERS.add("Chlopyralid");
        PARAMETERS.add("Chlopyrifos");
        PARAMETERS.add("Chloral Hydrate");
        PARAMETERS.add("Chlorate");
        PARAMETERS.add("Chlordane");
        PARAMETERS.add("Chlordane Gamma");
        PARAMETERS.add("Chlordane-alpha");
        PARAMETERS.add("Chlordane-cis");
        PARAMETERS.add("Chlordane-gamma");
        PARAMETERS.add("Chlordane-trans");
        PARAMETERS.add("Chlorfenvinphos");
        PARAMETERS.add("Chloride");
        PARAMETERS.add("Chlorine");
        PARAMETERS.add("Chlorine Dioxide");
        PARAMETERS.add("Chlorite");
        PARAMETERS.add("Chlormequat");
        PARAMETERS.add("Chloro-2, nitrobenzene");
        PARAMETERS.add("Chloro-2,4-dinitrobenzene");
        PARAMETERS.add("Chloro-3, nitrobenzene");
        PARAMETERS.add("Chloro-4, nitrobenzene");
        PARAMETERS.add("Chloroacetaldehyde");
        PARAMETERS.add("Chlorobenzene");
        PARAMETERS.add("Chlorobenzilate");
        PARAMETERS.add("Chlorodibromomethane");
        PARAMETERS.add("Chlorodifluoromethane");
        PARAMETERS.add("Chloroethane");
        PARAMETERS.add("Chloroethene");
        PARAMETERS.add("Chlorofenvinphos");
        PARAMETERS.add("Chlorofluoromethane");
        PARAMETERS.add("Chloroform");
        PARAMETERS.add("Chloromethane");
        PARAMETERS.add("Chloronitrotoluenes");
        PARAMETERS.add("Chlorophyll");
        PARAMETERS.add("Chlorophyll, Acetone Extract");
        PARAMETERS.add("Chlorosulphonic Acid");
        PARAMETERS.add("Chlorothalonil");
        PARAMETERS.add("Chlorotoluron");
        PARAMETERS.add("Chlorpropham");
        PARAMETERS.add("Chlorpyrifos");
        PARAMETERS.add("Chlorpyriphos");
        PARAMETERS.add("Chlorpyriphos Methyl");
        PARAMETERS.add("Chlorthalonil");
        PARAMETERS.add("Chlortoluron");
        PARAMETERS.add("Chromium");
        PARAMETERS.add("Chromium III");
        PARAMETERS.add("Chromium VI (Hexavalent)");
        PARAMETERS.add("Chromium(II) Compounds (As Cr)");
        PARAMETERS.add("Chromium(III) Compounds (As Cr)");
        PARAMETERS.add("Chromium(VI) Compounds (As Cr)");
        PARAMETERS.add("Chrysene");
        PARAMETERS.add("Cis Chlordane");
        PARAMETERS.add("cis-1,2 dichloroethylene");
        PARAMETERS.add("cis-1,2-DCE");
        PARAMETERS.add("cis-1,2-Dichloroethene");
        PARAMETERS.add("cis-1,3-Dichloropropene");
        PARAMETERS.add("cis-1,3-Dichloropropene m");
        PARAMETERS.add("Cis-Heptachlor Epoxide");
        PARAMETERS.add("Clock Reading (Leachate)");
        PARAMETERS.add("Clopyralid");
        PARAMETERS.add("Clostridium perfringens (Including Spores)");
        PARAMETERS.add("Cloud Cover");
        PARAMETERS.add("CO");
        PARAMETERS.add("CO2");
        PARAMETERS.add("Coal Tars");
        PARAMETERS.add("Cobalt");
        PARAMETERS.add("COD (Chemical Oxygen Demand)");
        PARAMETERS.add("Coliform 500 ml Sample");
        PARAMETERS.add("Coliform Bacteria");
        PARAMETERS.add("Coliforms - Total");
        PARAMETERS.add("Coliforms Total (liq)");
        PARAMETERS.add("Colony Counts");
        PARAMETERS.add("Colour");
        PARAMETERS.add("Colouration (After Filtration)");
        PARAMETERS.add("Colouration (After Simple Filtration)");
        PARAMETERS.add("Conductivity");
        PARAMETERS.add("Conductivity (field)");
        PARAMETERS.add("Conductivity @ 20C");
        PARAMETERS.add("Conductivity @ 25C");
        PARAMETERS.add("Copper");
        PARAMETERS.add("Copper - Dissolved, Filtered");
        PARAMETERS.add("Copper - Total Unfiltered");
        PARAMETERS.add("Cotton Dust");
        PARAMETERS.add("Coumaphos");
        PARAMETERS.add("cresol p");
        PARAMETERS.add("Cresols");
        PARAMETERS.add("Cryofluorane");
        PARAMETERS.add("Cumene");
        PARAMETERS.add("Cyanamide");
        PARAMETERS.add("Cyanazine");
        PARAMETERS.add("Cyanide");
        PARAMETERS.add("Cyanogen Chloride");
        PARAMETERS.add("Cyclohexane");
        PARAMETERS.add("Cyclohexanol");
        PARAMETERS.add("Cyclohexanone");
        PARAMETERS.add("Cyclohexylamine");
        PARAMETERS.add("Cyfluthrin");
        PARAMETERS.add("Cypermethrin");
        PARAMETERS.add("Date Lab Finished");
        PARAMETERS.add("Date Lab Started");
        PARAMETERS.add("Date Sample Arrived at Lab");
        PARAMETERS.add("DB Pressure");
        PARAMETERS.add("DB Temperature");
        PARAMETERS.add("DBP (Dibutyl Phthalate)");
        PARAMETERS.add("DCHP (Dicyclohexyl Phthalate)");
        PARAMETERS.add("DDD (O,P)");
        PARAMETERS.add("DDD (P,P)");
        PARAMETERS.add("DDE (O,P)");
        PARAMETERS.add("DDE (P,P)");
        PARAMETERS.add("DDT (Dichlorodiphenyltrichloroethane)");
        PARAMETERS.add("DDT (O,P)");
        PARAMETERS.add("DDT (P,P)");
        PARAMETERS.add("DDT Total");
        PARAMETERS.add("DEHP (Di(2-ethylhexyl) Phthalate)");
        PARAMETERS.add("delta-BHC");
        PARAMETERS.add("Demeton");
        PARAMETERS.add("Demeton-O");
        PARAMETERS.add("Demetons");
        PARAMETERS.add("Demeton-S-methyl");
        PARAMETERS.add("DEP (Diethyl Phthalate)");
        PARAMETERS.add("Deposited Dust");
        PARAMETERS.add("Desmetryne");
        PARAMETERS.add("Diallate");
        PARAMETERS.add("Diallyl Phthalate");
        PARAMETERS.add("Diatomaceous Earth, Natural, Respirable Dust");
        PARAMETERS.add("Diazinon");
        PARAMETERS.add("Dibenz(a,h)anthracene");
        PARAMETERS.add("Dibenz(a,h)anthracene (PAH)");
        PARAMETERS.add("Dibenzofuran");
        PARAMETERS.add("Dibenzothiophene");
        PARAMETERS.add("Dibenzoyl Peroxide");
        PARAMETERS.add("Dibismuth Tritelluride");
        PARAMETERS.add("Diboron Trioxide");
        PARAMETERS.add("Dibromo-3-chloropropane");
        PARAMETERS.add("Dibromoacetonitrile");
        PARAMETERS.add("Dibromochloromethane");
        PARAMETERS.add("Dibromofluoromethane");
        PARAMETERS.add("Dibromomethane");
        PARAMETERS.add("Dibutyl Hydrogen Phosphate");
        PARAMETERS.add("Dibutyl Tin");
        PARAMETERS.add("Dibutylbis(oxylauroyl)tin");
        PARAMETERS.add("Dicamba");
        PARAMETERS.add("Dichlobenil");
        PARAMETERS.add("Dichlofluanid");
        PARAMETERS.add("Dichloroacetate");
        PARAMETERS.add("Dichloroacetonitrile");
        PARAMETERS.add("Dichloroacetylene");
        PARAMETERS.add("Dichloroaniline");
        PARAMETERS.add("Dichlorobenzene");
        PARAMETERS.add("Dichlorobromethane");
        PARAMETERS.add("Dichlorodifluoromethane");
        PARAMETERS.add("Dichlorodiphenyldichloroethane");
        PARAMETERS.add("Dichlorodiphenyldichloroethylene");
        PARAMETERS.add("Dichlorofluoromethane");
        PARAMETERS.add("Dichloromethane");
        PARAMETERS.add("Dichloronitrobenzene");
        PARAMETERS.add("Dichlorophen");
        PARAMETERS.add("Dichlorprop");
        PARAMETERS.add("Dichlorvos");
        PARAMETERS.add("Diclofol");
        PARAMETERS.add("Dicyclopentadiene");
        PARAMETERS.add("Dieldrin");
        PARAMETERS.add("Diethyl Ether");
        PARAMETERS.add("Diethyl Sulphate");
        PARAMETERS.add("Diethylamine");
        PARAMETERS.add("Diethylphthalate");
        PARAMETERS.add("Differential Pressure");
        PARAMETERS.add("Diflubenzuron");
        PARAMETERS.add("Dihydrogen Selenide (As Se)");
        PARAMETERS.add("Diisobutyl Phthalate");
        PARAMETERS.add("Diisodecyl Phthalate");
        PARAMETERS.add("Diisononyl Phthalate");
        PARAMETERS.add("Diisooctyl Phthalate");
        PARAMETERS.add("Diisopropyl Ether");
        PARAMETERS.add("Diisopropylamine");
        PARAMETERS.add("Dimethoate");
        PARAMETERS.add("Dimethoxymethane");
        PARAMETERS.add("Dimethyl Ether");
        PARAMETERS.add("Dimethyl Sulphate");
        PARAMETERS.add("Dimethylamine");
        PARAMETERS.add("Dimethyldisulphide");
        PARAMETERS.add("Dimethylether");
        PARAMETERS.add("Dimethylethylphenol");
        PARAMETERS.add("Dimethylformamide");
        PARAMETERS.add("Dimethylphenols");
        PARAMETERS.add("Dimethylphthalate");
        PARAMETERS.add("Dimethylsulphide");
        PARAMETERS.add("Di-n-butyl phthalate");
        PARAMETERS.add("Dinitrobenzenes");
        PARAMETERS.add("Di-n-octyl phthalate");
        PARAMETERS.add("Dinonyl Phthalate");
        PARAMETERS.add("Dinoseb");
        PARAMETERS.add("Dioctyl Phthalate");
        PARAMETERS.add("Dioxin-like PCBs (WHO-TEQ  Birds)");
        PARAMETERS.add("Dioxin-like PCBs (WHO-TEQ  Fish)");
        PARAMETERS.add("Dioxin-like PCBs (WHO-TEQ Humans / Mammals)");
        PARAMETERS.add("Dioxins / furans (I-TEQ)");
        PARAMETERS.add("Dioxins / furans (WHO-TEQ Birds)");
        PARAMETERS.add("Dioxins / furans (WHO-TEQ Fish)");
        PARAMETERS.add("Dioxins / furans (WHO-TEQ Humans / Mammals)");
        PARAMETERS.add("Diphenyl Ether");
        PARAMETERS.add("Diphenylamine");
        PARAMETERS.add("Diphosphorus Pentasulphide");
        PARAMETERS.add("Diphosphorus Pentoxide");
        PARAMETERS.add("Dipropyl phthalate");
        PARAMETERS.add("Diquat Dibromide");
        PARAMETERS.add("Discharge Flow Rate");
        PARAMETERS.add("Discharge Rate Maximum");
        PARAMETERS.add("Discharge Volume Daily");
        PARAMETERS.add("Discharge Volume Monthly");
        PARAMETERS.add("Disodium Disulphite");
        PARAMETERS.add("Disodium Tetraborate Decahydrate");
        PARAMETERS.add("Disodium Tetraborate Pentahydrate");
        PARAMETERS.add("Disodium Tetraborate, Anhydrous");
        PARAMETERS.add("Dissolved or Emulsified Hydrocarbons");
        PARAMETERS.add("Dissolved Organic Carbon");
        PARAMETERS.add("Dissolved Oxygen");
        PARAMETERS.add("Disulfoton");
        PARAMETERS.add("Disulphur Dichloride");
        PARAMETERS.add("Diuron");
        PARAMETERS.add("DMP (Dimethyl Phthalate)");
        PARAMETERS.add("DO (Dissolved Oxygen)");
        PARAMETERS.add("DOPs (Dioctyl Phthalates)");
        PARAMETERS.add("Doramectin");
        PARAMETERS.add("DTPA");
        PARAMETERS.add("Dust");
        PARAMETERS.add("Dust Visible (Airborne)");
        PARAMETERS.add("E. Coli (faecal coliforms)");
        PARAMETERS.add("E.Coli");
        PARAMETERS.add("EDTA");
        PARAMETERS.add("EDTA (Edetic Acid)");
        PARAMETERS.add("Electrical Conductivity");
        PARAMETERS.add("Electrical Energy Exported");
        PARAMETERS.add("Electrical Energy Imported");
        PARAMETERS.add("Electrical Energy Used");
        PARAMETERS.add("Emery");
        PARAMETERS.add("Endosulfan");
        PARAMETERS.add("Endosulfan Sulphate");
        PARAMETERS.add("Endrin");
        PARAMETERS.add("Endrin aldehyde");
        PARAMETERS.add("Endrin Ketone");
        PARAMETERS.add("Enflurane");
        PARAMETERS.add("Entero Viruses");
        PARAMETERS.add("Enterococci");
        PARAMETERS.add("Environmental Tobacco Smoke (ETS)");
        PARAMETERS.add("Epichlorohydrin");
        PARAMETERS.add("Epoxyconazole");
        PARAMETERS.add("Equipment Calibration Due");
        PARAMETERS.add("Equipment Last Calibration");
        PARAMETERS.add("Equipment Serial No");
        PARAMETERS.add("Equipment Used");
        PARAMETERS.add("Escherichia coli (E.coli)");
        PARAMETERS.add("Ethanal");
        PARAMETERS.add("Ethane");
        PARAMETERS.add("Ethane-1,2-diol");
        PARAMETERS.add("Ethanethiol");
        PARAMETERS.add("Ethanol");
        PARAMETERS.add("Ethion");
        PARAMETERS.add("Ethoprop");
        PARAMETERS.add("Ethyl Acetate");
        PARAMETERS.add("Ethyl Acrylate");
        PARAMETERS.add("Ethyl Benzene");
        PARAMETERS.add("Ethyl butyrate");
        PARAMETERS.add("Ethyl Chloride");
        PARAMETERS.add("Ethyl Chloroformate");
        PARAMETERS.add("Ethyl Cyanoacrylate");
        PARAMETERS.add("Ethyl Formate");
        PARAMETERS.add("Ethyl methanesulfonate");
        PARAMETERS.add("Ethyl methyl Benzenesulphonamide");
        PARAMETERS.add("Ethylamine");
        PARAMETERS.add("Ethylbenzene");
        PARAMETERS.add("Ethylene");
        PARAMETERS.add("Ethylene Oxide");
        PARAMETERS.add("Ethylmethylbenzene");
        PARAMETERS.add("Etrimphos");
        PARAMETERS.add("Faecal Coliforms");
        PARAMETERS.add("Faecal Streptococci");
        PARAMETERS.add("Fenchlorophos");
        PARAMETERS.add("Fenchlorphos");
        PARAMETERS.add("Fenitrothion");
        PARAMETERS.add("Fenoprop");
        PARAMETERS.add("Fenpropimorph");
        PARAMETERS.add("Fensulfothion");
        PARAMETERS.add("Fenthion");
        PARAMETERS.add("Ferrous Foundry Particulate");
        PARAMETERS.add("Flammable Gas");
        PARAMETERS.add("Flare on/off");
        PARAMETERS.add("Flour Dust");
        PARAMETERS.add("Flow Rate");
        PARAMETERS.add("Flucofuron");
        PARAMETERS.add("Fluoranthene");
        PARAMETERS.add("Fluoranthene (PAH)");
        PARAMETERS.add("Fluorene");
        PARAMETERS.add("Fluoride");
        PARAMETERS.add("Fluorine");
        PARAMETERS.add("Fluroxypyr");
        PARAMETERS.add("Flusialzole");
        PARAMETERS.add("Flusilazole");
        PARAMETERS.add("Formaldehyde");
        PARAMETERS.add("Formaldehyde (HCHO)");
        PARAMETERS.add("Formamide");
        PARAMETERS.add("Formic Acid");
        PARAMETERS.add("Freon-11");
        PARAMETERS.add("Freon-113");
        PARAMETERS.add("Fuel Oil");
        PARAMETERS.add("Furan");
        PARAMETERS.add("gamma-BHC");
        PARAMETERS.add("Gas Analyser Run Time");
        PARAMETERS.add("Gas Flow");
        PARAMETERS.add("Gas Flow of Flare");
        PARAMETERS.add("Gas flow rate peak CH4");
        PARAMETERS.add("Gas flow rate peak CO2");
        PARAMETERS.add("Gas Flow Velocity");
        PARAMETERS.add("Gas Pressure");
        PARAMETERS.add("Gas Screen Value Carbon Dioxide");
        PARAMETERS.add("Gas Screen Value Methane");
        PARAMETERS.add("Gas Temp");
        PARAMETERS.add("Gas Utilisation");
        PARAMETERS.add("Gasoline Range Organics");
        PARAMETERS.add("Gasoline Range Organics C5-C12");
        PARAMETERS.add("Germane");
        PARAMETERS.add("Glutaraldehyde");
        PARAMETERS.add("Glycerol, Mist");
        PARAMETERS.add("Grain Dust");
        PARAMETERS.add("Graphite");
        PARAMETERS.add("GRO Surrogate");
        PARAMETERS.add("Groundwater Level");
        PARAMETERS.add("Gypsum");
        PARAMETERS.add("Haloforms Total");
        PARAMETERS.add("Halogenated Organic Compounds (total)");
        PARAMETERS.add("Halogenated Solvents");
        PARAMETERS.add("Halogenoplatinum Compounds (As Pt)");
        PARAMETERS.add("Halothane");
        PARAMETERS.add("Hardness");
        PARAMETERS.add("Hardness as CaCO3");
        PARAMETERS.add("Hardwood Dust");
        PARAMETERS.add("Hazardous Pollutants screen");
        PARAMETERS.add("HCH Total");
        PARAMETERS.add("HCH-alpha");
        PARAMETERS.add("HCH-beta");
        PARAMETERS.add("HCH-delta");
        PARAMETERS.add("HCH-epsilon");
        PARAMETERS.add("HCH-gamma");
        PARAMETERS.add("Heavy Metals");
        PARAMETERS.add("Helium");
        PARAMETERS.add("Heptachlor");
        PARAMETERS.add("Heptachlor Epoxide");
        PARAMETERS.add("Heptachlorepoxide");
        PARAMETERS.add("Heptan-2-one");
        PARAMETERS.add("Heptan-3-one");
        PARAMETERS.add("Heptanoic acid");
        PARAMETERS.add("Hexachlorobenzene");
        PARAMETERS.add("Hexachlorobutadiene");
        PARAMETERS.add("Hexachlorobutadiene STLPAM");
        PARAMETERS.add("Hexachlorobutadiene STLPJZ");
        PARAMETERS.add("Hexachlorocyclohexane");
        PARAMETERS.add("Hexachlorocyclopentadiene");
        PARAMETERS.add("Hexachloroethane");
        PARAMETERS.add("Hexachloronorbornadiene");
        PARAMETERS.add("Hexachloropropene");
        PARAMETERS.add("Hexaconazole");
        PARAMETERS.add("Hexan-2-one");
        PARAMETERS.add("Hexanes");
        PARAMETERS.add("Hexanoic acid");
        PARAMETERS.add("Hours Run");
        PARAMETERS.add("Hydrazine");
        PARAMETERS.add("Hydrocarbons");
        PARAMETERS.add("Hydrocarbons - total diesel range organics");
        PARAMETERS.add("Hydrocarbons - total minerals range organics");
        PARAMETERS.add("Hydrocarbons - total phenol range organics");
        PARAMETERS.add("Hydrocarbons - unburned");
        PARAMETERS.add("Hydrogen");
        PARAMETERS.add("Hydrogen Bromide");
        PARAMETERS.add("Hydrogen chloride");
        PARAMETERS.add("Hydrogen Chloride (Gas and Aerosol Mists)");
        PARAMETERS.add("Hydrogen Cyanide");
        PARAMETERS.add("Hydrogen fluoride");
        PARAMETERS.add("Hydrogen Fluoride (As F)");
        PARAMETERS.add("Hydrogen Ion Content");
        PARAMETERS.add("Hydrogen Peroxide");
        PARAMETERS.add("Hydrogen Sulphide");
        PARAMETERS.add("Hydrogen Sulphide POD");
        PARAMETERS.add("Hydroquinone");
        PARAMETERS.add("Imazethapyr");
        PARAMETERS.add("Indene");
        PARAMETERS.add("Indeno(1,2,3 cd)pyrene");
        PARAMETERS.add("Indeno[1,2,3-cd]pyrene");
        PARAMETERS.add("Indium and Its Compounds (As In)");
        PARAMETERS.add("Iodine");
        PARAMETERS.add("Iodoform");
        PARAMETERS.add("Iodomethane");
        PARAMETERS.add("Ionic Balance");
        PARAMETERS.add("Ioxynil");
        PARAMETERS.add("Iron");
        PARAMETERS.add("Iron - Total Unfiltered");
        PARAMETERS.add("Iron Oxide, Fume (As Fe)");
        PARAMETERS.add("Iron Salts (As Fe)");
        PARAMETERS.add("Isobutyl Acetate");
        PARAMETERS.add("iso-Butyric acid");
        PARAMETERS.add("iso-Caproic acid");
        PARAMETERS.add("Isocyanates, All (As -NCO)");
        PARAMETERS.add("Isodrin");
        PARAMETERS.add("Isoflurane");
        PARAMETERS.add("Isooctyl Alcohol");
        PARAMETERS.add("Isopentane");
        PARAMETERS.add("Isophorone");
        PARAMETERS.add("Isopropyl Acetate");
        PARAMETERS.add("Isopropyl Chloroformate");
        PARAMETERS.add("Isopropylbenzene");
        PARAMETERS.add("iso-propyltoluene");
        PARAMETERS.add("Isoproturon");
        PARAMETERS.add("Isosafrole");
        PARAMETERS.add("iso-Valeric acid");
        PARAMETERS.add("Ivermectin");
        PARAMETERS.add("Kaolin, Respirable Dust");
        PARAMETERS.add("Kepone");
        PARAMETERS.add("Ketene");
        PARAMETERS.add("Kresoxym-methyl");
        PARAMETERS.add("Lab Job No");
        PARAMETERS.add("Lab Sample Ref");
        PARAMETERS.add("Lab Status");
        PARAMETERS.add("Lab Turnaround Total Days");
        PARAMETERS.add("Laboratory Used");
        PARAMETERS.add("Leachate Level");
        PARAMETERS.add("Lead");
        PARAMETERS.add("LEL");
        PARAMETERS.add("Lime");
        PARAMETERS.add("Limestone");
        PARAMETERS.add("Lindane");
        PARAMETERS.add("Lindane-delta");
        PARAMETERS.add("Linuron");
        PARAMETERS.add("Liquefied Petroleum Gas");
        PARAMETERS.add("Lithium");
        PARAMETERS.add("Lithium Hydride");
        PARAMETERS.add("Lithium Hydroxide");
        PARAMETERS.add("Lithium, Dissolved");
        PARAMETERS.add("Magnesite");
        PARAMETERS.add("Magnesium");
        PARAMETERS.add("Magnesium Hardness as CaCO3");
        PARAMETERS.add("Magnesium Oxide (As Mg)");
        PARAMETERS.add("Malachite Green");
        PARAMETERS.add("Malathion");
        PARAMETERS.add("Maleic Anhydride");
        PARAMETERS.add("Mancozeb");
        PARAMETERS.add("Maneb");
        PARAMETERS.add("Manganese");
        PARAMETERS.add("Man-Made Vitreous Fibres (MMVF)");
        PARAMETERS.add("Marble");
        PARAMETERS.add("Maximum Daily Flow");
        PARAMETERS.add("MCPA");
        PARAMETERS.add("MCPA ((4-Chloro-2-methylphenoxy)acetic Acid)");
        PARAMETERS.add("MCPB");
        PARAMETERS.add("Mean Daily Flow");
        PARAMETERS.add("Mecoprop");
        PARAMETERS.add("Mercaptoacetic Acid");
        PARAMETERS.add("Mercury");
        PARAMETERS.add("Mercury (II) nitrate");
        PARAMETERS.add("Mercury and its compounds");
        PARAMETERS.add("Mercury and its compounds expressed as Mercury (Total Hg)");
        PARAMETERS.add("Merphos");
        PARAMETERS.add("Mesosulfuron-methyl");
        PARAMETERS.add("Metalaxyl");
        PARAMETERS.add("Metaldehyde");
        PARAMETERS.add("Metals Total and Dissolved ( Zn, CU, Cd, Pb, Ni, Hg )");
        PARAMETERS.add("Methabenzthiazuron");
        PARAMETERS.add("Methacriphos");
        PARAMETERS.add("Methacrylic Acid");
        PARAMETERS.add("Methacrylonitrile");
        PARAMETERS.add("Methanal");
        PARAMETERS.add("Methane");
        PARAMETERS.add("Methane Flux");
        PARAMETERS.add("Methane Peak");
        PARAMETERS.add("Methanethiol");
        PARAMETERS.add("Methanol");
        PARAMETERS.add("Methiocarb");
        PARAMETERS.add("Methoxychlor");
        PARAMETERS.add("Methoxychlor o,p");
        PARAMETERS.add("Methoxychlor p,p");
        PARAMETERS.add("Methyl Acetate");
        PARAMETERS.add("Methyl Cyanoacrylate");
        PARAMETERS.add("Methyl Ethyl Ketone Peroxides (MEKP)");
        PARAMETERS.add("Methyl ethyl phenol");
        PARAMETERS.add("Methyl Methacrylate");
        PARAMETERS.add("Methyl tert-Butyl Ether");
        PARAMETERS.add("Methyl tertiary-butyl ether (MTBE)");
        PARAMETERS.add("Methylcyclohexanol");
        PARAMETERS.add("Methylene Chloride");
        PARAMETERS.add("Methylparathion");
        PARAMETERS.add("Methylphenols");
        PARAMETERS.add("Metolachlor");
        PARAMETERS.add("Mevinphos");
        PARAMETERS.add("Mica");
        PARAMETERS.add("Microcystin-LR");
        PARAMETERS.add("Mineral Oil");
        PARAMETERS.add("Mineral Oils");
        PARAMETERS.add("Mineral Oils and Hydrocarbons");
        PARAMETERS.add("MMMF (Machine-Made Mineral Fibre)");
        PARAMETERS.add("Molinate");
        PARAMETERS.add("Molybdenum");
        PARAMETERS.add("Monlinuron");
        PARAMETERS.add("Monobutyl Tin as Cation");
        PARAMETERS.add("Monochloramine");
        PARAMETERS.add("Monochloroacetic Acid");
        PARAMETERS.add("Monuron");
        PARAMETERS.add("Morpholine");
        PARAMETERS.add("Mthe");
        PARAMETERS.add("N,N-Dimethylacetamide");
        PARAMETERS.add("N,N-Dimethylaniline");
        PARAMETERS.add("N,N-Dimethylethylamine");
        PARAMETERS.add("Naled");
        PARAMETERS.add("Naphthalene");
        PARAMETERS.add("National Grid Ref");
        PARAMETERS.add("n-Butyl Acrylate");
        PARAMETERS.add("n-Butyl Chloroformate");
        PARAMETERS.add("n-Butylbenzene");
        PARAMETERS.add("n-Butyric acid");
        PARAMETERS.add("n-Caproic acid");
        PARAMETERS.add("n-Dibutyl phthalate");
        PARAMETERS.add("Neopentane");
        PARAMETERS.add("Net total annual production");
        PARAMETERS.add("n-Heptane");
        PARAMETERS.add("n-Hexane");
        PARAMETERS.add("Nickel");
        PARAMETERS.add("Nicotine");
        PARAMETERS.add("Nitrate");
        PARAMETERS.add("Nitric Acid");
        PARAMETERS.add("Nitrite");
        PARAMETERS.add("Nitrobenzene");
        PARAMETERS.add("Nitrogen");
        PARAMETERS.add("Nitrogen Dioxide");
        PARAMETERS.add("Nitrogen Oxides");
        PARAMETERS.add("Nitromethane");
        PARAMETERS.add("Nitrous Oxide");
        PARAMETERS.add("Nitrous oxide (N2O)");
        PARAMETERS.add("N-Methylaniline");
        PARAMETERS.add("NMVOCs");
        PARAMETERS.add("n-Nitrosodiethylamine");
        PARAMETERS.add("n-Nitrosodimethylamine");
        PARAMETERS.add("n-Nitroso-di-N-butylamine");
        PARAMETERS.add("n-Nitroso-di-n-propylamine");
        PARAMETERS.add("n-Nitrosodiphenylamine");
        PARAMETERS.add("n-Nitrosomethylethylamine");
        PARAMETERS.add("n-Nitrosopiperidine");
        PARAMETERS.add("n-Nitrosopyrrolidine");
        PARAMETERS.add("Nonylphenol");
        PARAMETERS.add("Nonylphenol ethoxylate");
        PARAMETERS.add("Nonylphenols");
        PARAMETERS.add("NOX");
        PARAMETERS.add("n-Propyl Acetate");
        PARAMETERS.add("n-Propylbenzene");
        PARAMETERS.add("NTA (Nitrilotriacetic Acid)");
        PARAMETERS.add("n-Valeric acid");
        PARAMETERS.add("O2");
        PARAMETERS.add("o-Acetylsalicyclic Acid");
        PARAMETERS.add("o-Chlorotoluene");
        PARAMETERS.add("Octylphenol");
        PARAMETERS.add("Octylphenols");
        PARAMETERS.add("Odour");
        PARAMETERS.add("Odour Description");
        PARAMETERS.add("Odour Extent");
        PARAMETERS.add("Odour Intensity");
        PARAMETERS.add("Oil and Grease");
        PARAMETERS.add("Oil and Grease (Visual)");
        PARAMETERS.add("Oil and Grease Saponifiable");
        PARAMETERS.add("Oil and Grease Unsaponifiable");
        PARAMETERS.add("Oil/Grease");
        PARAMETERS.add("Omethoate");
        PARAMETERS.add("Organochlorine Pesticides");
        PARAMETERS.add("Organohalogens");
        PARAMETERS.add("Organophosphorous compounds");
        PARAMETERS.add("Organophosphorus Compounds");
        PARAMETERS.add("Organotin compounds");
        PARAMETERS.add("Orthophosphate");
        PARAMETERS.add("Orthophosphoric Acid");
        PARAMETERS.add("Osmium Tetraoxide (As Os)");
        PARAMETERS.add("Other Energy Produced");
        PARAMETERS.add("Other inputs of water/moisture");
        PARAMETERS.add("Other Solid Residues");
        PARAMETERS.add("o-Toluidene");
        PARAMETERS.add("o-toluidine");
        PARAMETERS.add("Oxalic Acid");
        PARAMETERS.add("Oxides of Nitrogen (NO and NO2 expressed as NO2)");
        PARAMETERS.add("Oxidisability");
        PARAMETERS.add("Oxydemeton-methyl");
        PARAMETERS.add("Oxygen");
        PARAMETERS.add("Ozone");
        PARAMETERS.add("p,p-DDT (1,1,1-Trichloro-2,2-bis(4-chlorophenyl)ethane)");
        PARAMETERS.add("PAHs (Polycyclic Aromatic Hydrocarbons)");
        PARAMETERS.add("Paracetamol, Inhalable Dust");
        PARAMETERS.add("Paraffin Wax, Fume");
        PARAMETERS.add("p-Aramid Respirable Fibres");
        PARAMETERS.add("Paraquat Dichloride, Respirable Dust");
        PARAMETERS.add("Parathion");
        PARAMETERS.add("Parathion-ethyl");
        PARAMETERS.add("Parathion-methyl");
        PARAMETERS.add("Particles");
        PARAMETERS.add("Particles (PM10)");
        PARAMETERS.add("Particulates");
        PARAMETERS.add("Particulates (PM10)");
        PARAMETERS.add("PCB101");
        PARAMETERS.add("PCB118");
        PARAMETERS.add("PCB123");
        PARAMETERS.add("PCB138");
        PARAMETERS.add("PCB153");
        PARAMETERS.add("PCB180");
        PARAMETERS.add("PCB28");
        PARAMETERS.add("PCB52");
        PARAMETERS.add("PCBs (Polychlorinated Biphenyls)");
        PARAMETERS.add("PCDDs and PCDFs (Polychlorinated Dibenzodioxins and Dibenzofurans)");
        PARAMETERS.add("p-Chloroaniline");
        PARAMETERS.add("p-Chlorotoluene");
        PARAMETERS.add("PCSDs");
        PARAMETERS.add("p-Dimethylaminoazobenzene");
        PARAMETERS.add("Pendimethalin");
        PARAMETERS.add("penta-BDPE (Pentabromodiphenyl Ether)");
        PARAMETERS.add("Pentacarbonyliron (As Fe)");
        PARAMETERS.add("Pentachlorobenzene");
        PARAMETERS.add("Pentachloroethane");
        PARAMETERS.add("Pentachloronitrobenzene");
        PARAMETERS.add("Pentachlorophenol");
        PARAMETERS.add("Pentachlorophenol (PCP)");
        PARAMETERS.add("Pentaerythritol");
        PARAMETERS.add("Pentan-2-one");
        PARAMETERS.add("Pentan-3-one");
        PARAMETERS.add("Pentane");
        PARAMETERS.add("Pentanes");
        PARAMETERS.add("Pentyl Acetates (All Isomers)");
        PARAMETERS.add("Perfluorooctane Acid");
        PARAMETERS.add("Perfluorooctane Sulphonate");
        PARAMETERS.add("Permanganate value");
        PARAMETERS.add("Permethrin");
        PARAMETERS.add("Personnel");
        PARAMETERS.add("Pesticides - Total");
        PARAMETERS.add("Pesticides (Other Than Aldrin, Dieldrin, Heptachlor, Heptachlor Epoxide)");
        PARAMETERS.add("Petroleum Hydrocarbons");
        PARAMETERS.add("pH");
        PARAMETERS.add("Phenanthrene");
        PARAMETERS.add("Phenanthrene ESG SVOC");
        PARAMETERS.add("Phenol");
        PARAMETERS.add("Phenolic Compounds");
        PARAMETERS.add("Phenols");
        PARAMETERS.add("Phenols (Phenol Index) Paranitraniline 4-Aminoantipyrene");
        PARAMETERS.add("Phenols Monohydric");
        PARAMETERS.add("Phenylamine");
        PARAMETERS.add("Phorate");
        PARAMETERS.add("Phosalone");
        PARAMETERS.add("Phosfamidon");
        PARAMETERS.add("Phosgene");
        PARAMETERS.add("Phosphates");
        PARAMETERS.add("Phosphine");
        PARAMETERS.add("Phosphorus");
        PARAMETERS.add("Phosphorus Pentachloride");
        PARAMETERS.add("Phosphorus Trichloride");
        PARAMETERS.add("Phosphorus, soluble reactive");
        PARAMETERS.add("Phosphorus, Total Inorganic");
        PARAMETERS.add("Phosphoryl Trichloride");
        PARAMETERS.add("Phthalic Anhydride");
        PARAMETERS.add("Picloram");
        PARAMETERS.add("Picric Acid");
        PARAMETERS.add("Piperazine");
        PARAMETERS.add("Piperazine Dihydrochloride");
        PARAMETERS.add("Piperidine");
        PARAMETERS.add("Pirimicarb");
        PARAMETERS.add("Pirimiphos-ethyl");
        PARAMETERS.add("Pirimiphos-methyl");
        PARAMETERS.add("p-isopropyltoluene");
        PARAMETERS.add("Plaster of Paris");
        PARAMETERS.add("Plate Count 22C");
        PARAMETERS.add("Plate Count 37C");
        PARAMETERS.add("Platinum");
        PARAMETERS.add("Platinum Compounds, Soluble (As Pt)");
        PARAMETERS.add("PM10 24hra");
        PARAMETERS.add("PM10 in Air");
        PARAMETERS.add("PM2.5 24hra");
        PARAMETERS.add("Poisonous substances");
        PARAMETERS.add("Polyvinyl Chloride");
        PARAMETERS.add("Portland Cement");
        PARAMETERS.add("Potassium");
        PARAMETERS.add("Potassium Hydroxide");
        PARAMETERS.add("Power Generated");
        PARAMETERS.add("p-Phenylenediamine");
        PARAMETERS.add("Precipitation");
        PARAMETERS.add("Pressure");
        PARAMETERS.add("Presumptive Clostridia");
        PARAMETERS.add("Presumptive F.Coli");
        PARAMETERS.add("Presumptive T.Coli");
        PARAMETERS.add("PresumptiveEnterococci");
        PARAMETERS.add("Prochloraz");
        PARAMETERS.add("Prometon");
        PARAMETERS.add("Prometryne");
        PARAMETERS.add("Pronamide");
        PARAMETERS.add("Prop-2-yn-1-ol");
        PARAMETERS.add("Propan-1-ol");
        PARAMETERS.add("Propan-2-ol");
        PARAMETERS.add("Propane");
        PARAMETERS.add("Propane-1,2-diol");
        PARAMETERS.add("Propanil");
        PARAMETERS.add("Propazine");
        PARAMETERS.add("Propetamphos");
        PARAMETERS.add("Propionic Acid");
        PARAMETERS.add("Propoxur");
        PARAMETERS.add("Propranolol");
        PARAMETERS.add("Propylbenzene");
        PARAMETERS.add("Propylene");
        PARAMETERS.add("Propylene Oxide");
        PARAMETERS.add("Propyzamide");
        PARAMETERS.add("Pseudomonas aeruginosa");
        PARAMETERS.add("p-Toluenesulphonyl Chloride");
        PARAMETERS.add("Pulse Count");
        PARAMETERS.add("Pulverised Fuel Ash");
        PARAMETERS.add("Pump count value");
        PARAMETERS.add("Pump Valve position On/Off");
        PARAMETERS.add("Purge Volume");
        PARAMETERS.add("Purged Water Volume");
        PARAMETERS.add("Pyrene");
        PARAMETERS.add("Pyrethrum");
        PARAMETERS.add("Pyridine");
        PARAMETERS.add("Pyriproxyfen");
        PARAMETERS.add("Pyrocatechol");
        PARAMETERS.add("Quantity Waste Incinerated");
        PARAMETERS.add("Radon");
        PARAMETERS.add("Rapidly settleable solids");
        PARAMETERS.add("Reason for not sampling");
        PARAMETERS.add("Redox Potential");
        PARAMETERS.add("Refractory Ceramic Fibres and Special Purpose Fibres");
        PARAMETERS.add("Relative Pressure");
        PARAMETERS.add("Residual Organic Carbon");
        PARAMETERS.add("Resorcinol");
        PARAMETERS.add("Response Zone");
        PARAMETERS.add("Retention Time");
        PARAMETERS.add("Rhodium (As Rh)");
        PARAMETERS.add("Rising/Falling");
        PARAMETERS.add("Ronnel");
        PARAMETERS.add("Rosin-Based Solder Flux Fume");
        PARAMETERS.add("Rotenone");
        PARAMETERS.add("Rouge");
        PARAMETERS.add("Rubber Fume");
        PARAMETERS.add("Rubber Process Dust");
        PARAMETERS.add("Safrole");
        PARAMETERS.add("Salinity");
        PARAMETERS.add("Salmonella");
        PARAMETERS.add("Sample Method");
        PARAMETERS.add("Sample Ref No");
        PARAMETERS.add("Sampler Name");
        PARAMETERS.add("Saturation Depth");
        PARAMETERS.add("Saxitoxin");
        PARAMETERS.add("Sb, As, Pb, Cr, Co, Cu, Mn, Ni and V and their compounds (total)");
        PARAMETERS.add("Secbumeton");
        PARAMETERS.add("sec-Butyl Acetate");
        PARAMETERS.add("sec-Butylbenzene");
        PARAMETERS.add("Selenium");
        PARAMETERS.add("Settleable solids");
        PARAMETERS.add("Silane");
        PARAMETERS.add("Silica as SiO2");
        PARAMETERS.add("Silica, Amorphous");
        PARAMETERS.add("Silica, Fused Respirable Dust");
        PARAMETERS.add("Silica, Respirable Crystalline");
        PARAMETERS.add("Silicon");
        PARAMETERS.add("Silicon (Organic Compounds of)");
        PARAMETERS.add("Silicon Carbide (Not Whiskers)");
        PARAMETERS.add("Silver");
        PARAMETERS.add("Silver Compounds, Soluble (As Ag)");
        PARAMETERS.add("Simazine");
        PARAMETERS.add("Site Weather Conditions");
        PARAMETERS.add("Sodium");
        PARAMETERS.add("Sodium 2-(2,4-Dichlorophenoxy)ethyl Sulphate");
        PARAMETERS.add("Sodium Azide");
        PARAMETERS.add("Sodium Hydrogen Sulphite");
        PARAMETERS.add("Sodium Hydroxide");
        PARAMETERS.add("Softwood Dust");
        PARAMETERS.add("Solids, Ashed STL008");
        PARAMETERS.add("Solvent Extractable Matter");
        PARAMETERS.add("Solvents Aromatic total");
        PARAMETERS.add("SOX");
        PARAMETERS.add("Specific individual poly-cyclic aromatic hydrocarbons (PAHs)");
        PARAMETERS.add("Stack gas pressure");
        PARAMETERS.add("Stack gas temperature");
        PARAMETERS.add("Starch");
        PARAMETERS.add("Stirofos");
        PARAMETERS.add("Strontium");
        PARAMETERS.add("Strontium, Filtered");
        PARAMETERS.add("Styrene");
        PARAMETERS.add("Substances Affecting the Taste of the Shellfish");
        PARAMETERS.add("Substances Extractable with Chloroform");
        PARAMETERS.add("Substances Possessing Carcinogenic, Mutagenic or Teratogenic Properties in or via the Aquatic Environment");
        PARAMETERS.add("Subtilisins");
        PARAMETERS.add("Sucrose");
        PARAMETERS.add("Sulcofuron");
        PARAMETERS.add("Sulfotep");
        PARAMETERS.add("Sulphate");
        PARAMETERS.add("Sulphide");
        PARAMETERS.add("Sulphite-reducing Clostridia");
        PARAMETERS.add("Sulphur");
        PARAMETERS.add("Sulphur dioxide");
        PARAMETERS.add("Sulphur Hexafluoride");
        PARAMETERS.add("Sulphuryl Difluoride");
        PARAMETERS.add("Surface-Active Substances Reacting with Methylene Blue (Lauryl Sulphate)");
        PARAMETERS.add("Suspended Solids");
        PARAMETERS.add("SVOC");
        PARAMETERS.add("SVOC TICS");
        PARAMETERS.add("SVOCs");
        PARAMETERS.add("Symetryn");
        PARAMETERS.add("Talc, Respirable Dust");
        PARAMETERS.add("Tantalum");
        PARAMETERS.add("Tarry Residues and Floating Materials");
        PARAMETERS.add("Taste");
        PARAMETERS.add("TDE (O,P)");
        PARAMETERS.add("TDE (P,P)");
        PARAMETERS.add("Tebuconazole");
        PARAMETERS.add("Tecnazene");
        PARAMETERS.add("Tedlar Bag Details");
        PARAMETERS.add("Tellurium");
        PARAMETERS.add("Temp");
        PARAMETERS.add("Temperature");
        PARAMETERS.add("Terbuthylazine");
        PARAMETERS.add("Terbutryn");
        PARAMETERS.add("Terphenyl-d14");
        PARAMETERS.add("Terphenyls");
        PARAMETERS.add("Terpin monohydrate");
        PARAMETERS.add("tert-Amyl methyl ether");
        PARAMETERS.add("tert-Butyl Acetate");
        PARAMETERS.add("tert-Butylbenzene");
        PARAMETERS.add("tert-Butylmethylether");
        PARAMETERS.add("tert-Butylphenol");
        PARAMETERS.add("Tetra and Trichloroethene");
        PARAMETERS.add("Tetrabutyl tin");
        PARAMETERS.add("Tetracarbonylnickel (As Ni)");
        PARAMETERS.add("Tetrachlorobenzene");
        PARAMETERS.add("Tetrachloroethane");
        PARAMETERS.add("Tetrachloroethene");
        PARAMETERS.add("Tetrachloroethene (Perchloroethene)");
        PARAMETERS.add("Tetrachloroethylene");
        PARAMETERS.add("Tetrachloromethane");
        PARAMETERS.add("Tetrachloromethane (Carbon Tetrachloride)");
        PARAMETERS.add("Tetradecanoic acid");
        PARAMETERS.add("Tetrahydrofuran");
        PARAMETERS.add("Tetrasodium Pyrophosphate");
        PARAMETERS.add("Thallium");
        PARAMETERS.add("Thiabendazole");
        PARAMETERS.add("Thiocyanate");
        PARAMETERS.add("Thionyl Chloride");
        PARAMETERS.add("Time Sample Ended");
        PARAMETERS.add("Time Sample Started");
        PARAMETERS.add("Tin");
        PARAMETERS.add("Tin Compounds, Inorganic");
        PARAMETERS.add("Titanium");
        PARAMETERS.add("Titanium Dioxide");
        PARAMETERS.add("TOC (Total Organic Carbon)");
        PARAMETERS.add("Tokuthion");
        PARAMETERS.add("Tolex");
        PARAMETERS.add("Toluene");
        PARAMETERS.add("Toluene Extractable Matter");
        PARAMETERS.add("Total Acidity");
        PARAMETERS.add("Total Chlorinated Hydrocarbons");
        PARAMETERS.add("Total daily volume of discharge");
        PARAMETERS.add("Total Indicative Dose (for Radioactivity)");
        PARAMETERS.add("Total Inhalable Dust");
        PARAMETERS.add("Total Nitrogen");
        PARAMETERS.add("Total Organic Carbon (TOC)");
        PARAMETERS.add("Total Oxidised Nitrogen (TON)");
        PARAMETERS.add("Total Pesticides");
        PARAMETERS.add("Total Petroleum Hydrocarbons");
        PARAMETERS.add("Total phosphorus");
        PARAMETERS.add("Total suspended solids (TSS)");
        PARAMETERS.add("Total suspended solids (TSS) Spot sample");
        PARAMETERS.add("Total Volatile Substances (TVS)");
        PARAMETERS.add("TPH");
        PARAMETERS.add("TPH Aliphatics");
        PARAMETERS.add("TPH Aqueous Phase");
        PARAMETERS.add("TPH Aromatics");
        PARAMETERS.add("TPH C10-C12");
        PARAMETERS.add("TPH C10-C16");
        PARAMETERS.add("TPH C10-C20");
        PARAMETERS.add("TPH C10-C21");
        PARAMETERS.add("TPH C10-C39");
        PARAMETERS.add("TPH C10-C40");
        PARAMETERS.add("TPH C11-C12");
        PARAMETERS.add("TPH C12-C16");
        PARAMETERS.add("TPH C16-C21");
        PARAMETERS.add("TPH C16-C24");
        PARAMETERS.add("TPH C20-C40");
        PARAMETERS.add("TPH C21-C35");
        PARAMETERS.add("TPH C21-C40");
        PARAMETERS.add("TPH C24-C40");
        PARAMETERS.add("TPH C35-C39");
        PARAMETERS.add("TPH C5-C10");
        PARAMETERS.add("TPH C5-C35");
        PARAMETERS.add("TPH C6-C10");
        PARAMETERS.add("TPH C6-C40");
        PARAMETERS.add("TPH C6-C8");
        PARAMETERS.add("TPH C8-C10");
        PARAMETERS.add("TPH C8-C40");
        PARAMETERS.add("TPH C9-C40");
        PARAMETERS.add("TPH GC");
        PARAMETERS.add("Trans Chlordane");
        PARAMETERS.add("trans-1,2-Dichloroethane");
        PARAMETERS.add("trans-1,2-Dichloroethene");
        PARAMETERS.add("trans-1,3-Dichloropropene");
        PARAMETERS.add("Transparency");
        PARAMETERS.add("Triadimefon");
        PARAMETERS.add("Triallate");
        PARAMETERS.add("Triazophos");
        PARAMETERS.add("Tribromomethane");
        PARAMETERS.add("Tributlytin oxide (TBTO)");
        PARAMETERS.add("Tributyl Phosphate");
        PARAMETERS.add("Tributyltin");
        PARAMETERS.add("Tributyltin Compounds");
        PARAMETERS.add("Trichlorfon");
        PARAMETERS.add("Trichlorinate");
        PARAMETERS.add("Trichloro-2(2chlorophenyl)2ethane opDDT");
        PARAMETERS.add("Trichloroacetate");
        PARAMETERS.add("Trichlorobenzene");
        PARAMETERS.add("Trichlorobenzene (total)");
        PARAMETERS.add("Trichloroethane");
        PARAMETERS.add("Trichloroethene");
        PARAMETERS.add("Trichloroethene (Trichloroethylene)");
        PARAMETERS.add("Trichloroethylene");
        PARAMETERS.add("Trichlorofluoromethane");
        PARAMETERS.add("Trichloronitromethane");
        PARAMETERS.add("Triclorpyr");
        PARAMETERS.add("Trietazine");
        PARAMETERS.add("Triethylamine");
        PARAMETERS.add("Trifluralin");
        PARAMETERS.add("Triglycidyl Isocyanurate (TGIC)");
        PARAMETERS.add("Trihalomethanes");
        PARAMETERS.add("Trihalomethanes (total)");
        PARAMETERS.add("Trimellitic Anhydride");
        PARAMETERS.add("Trimethyl ester phosphoric acid");
        PARAMETERS.add("Trimethyl hexanoic acid");
        PARAMETERS.add("Trimethyl Phosphite");
        PARAMETERS.add("Trimethylbenzenes");
        PARAMETERS.add("Trimethyl-benzenesulphonamide");
        PARAMETERS.add("Trimethylphenols");
        PARAMETERS.add("Tri-o-tolyl Phosphate");
        PARAMETERS.add("Triphenyl Phosphate");
        PARAMETERS.add("Triphenyltin");
        PARAMETERS.add("Triphenyltin and Its Derivatives");
        PARAMETERS.add("Triphenyltin oxide (TPTO)");
        PARAMETERS.add("Tritium");
        PARAMETERS.add("Tungsten and Its Compounds (As W)");
        PARAMETERS.add("Turbidity");
        PARAMETERS.add("Turpentine");
        PARAMETERS.add("TVA");
        PARAMETERS.add("Type");
        PARAMETERS.add("Unidentified Peak");
        PARAMETERS.add("Uranium");
        PARAMETERS.add("Urea");
        PARAMETERS.add("Valeric acid");
        PARAMETERS.add("Valve Opened");
        PARAMETERS.add("Valve Position");
        PARAMETERS.add("Valve Turn Position After");
        PARAMETERS.add("Valve Turn Position Before");
        PARAMETERS.add("Vanadium");
        PARAMETERS.add("Vanadium Pentoxide");
        PARAMETERS.add("Vinyl Chloride");
        PARAMETERS.add("Visual Inspection (insitu)");
        PARAMETERS.add("VOC with TICs");
        PARAMETERS.add("VOCs");
        PARAMETERS.add("Volatile Acid Total");
        PARAMETERS.add("Volatile Fatty Acids C1-C6");
        PARAMETERS.add("Volatile organic Compounds (VOCs) (as carbon)");
        PARAMETERS.add("Volume");
        PARAMETERS.add("Waste/raw material inputs");
        PARAMETERS.add("Waste/raw material outputs");
        PARAMETERS.add("Water inputs to the Mill");
        PARAMETERS.add("Water outputs");
        PARAMETERS.add("Water used in manufacturing");
        PARAMETERS.add("Water vapour");
        PARAMETERS.add("Wind Direction");
        PARAMETERS.add("Wind Speed");
        PARAMETERS.add("Wool Process Dust");
        PARAMETERS.add("Xylenes");
        PARAMETERS.add("Xylenols");
        PARAMETERS.add("Yttrium");
        PARAMETERS.add("Zinc");
        PARAMETERS.add("Zinc Chloride, Fume");
        PARAMETERS.add("Zinc Distearate");
        PARAMETERS.add("Zirconium Compounds (As Zr) Bottom of Form");
        PARAMETERS.add("Temperature");
        PARAMETERS.add("sulphur oxides");
        PARAMETERS.add("Oxygen");
        PARAMETERS.add("Methane");
        PARAMETERS.add("mono-nitrogen oxides NO and NO₂");
	}

	/**
	 * 
	 */
	public ParameterListAuditor() {
	}

	/* (non-Javadoc)
	 * @see uk.gov.ea.datareturns.domain.model.validation.constraints.controlledlist.ControlledListAuditor#isValid(java.lang.Object)
	 */
	@Override
	public boolean isValid(Object value) {
		return PARAMETERS.contains(value);
	}

}
