###############################################################################
#
# Data Returns Master Data API Configuration Settings
#
###############################################################################
spring:
  application:
    name: Data Returns Master Data API
  datasource:
    url: jdbc:postgresql://localhost:5432/dr_md_api
    username: data_returns_owner
    password: data_returns_owner
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  display-name: dr_md_api
  port: 9020

---
###############################################################################
#
# Profile: h2
#
###############################################################################
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Enable liquibase migrations when running in-memory
liquibase:
  enabled: true

# Load master data at startup when running in-memory
dataloader:
  run-at-startup: true
  shutdown-after-load: false

---
###############################################################################
#
# Profile: dataloader
#
###############################################################################
spring:
  profiles: dataloader
  main:
    web-environment: false

dataloader:
  run-at-startup: true
  shutdown-after-load: true