###############################################################################
#
# Data Returns PI Submissions API Configuration Settings
#
# This file is split into different sections, the first provides defaults
# for all environments.  Subsequent sections provide profile-specific
# configurations which may be enabled to override the default values.
#
###############################################################################
spring:
  application:
    name: Data Returns PI Submissions API
  datasource:
    url: jdbc:postgresql://localhost:5432/dr_pi_api
    username: data_returns_owner
    password: data_returns_owner
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

# Configuration for the web server
server:
  display-name: dr_pi_api
  port: 9220

---
###############################################################################
#
# Profile: h2
#
###############################################################################
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Enable liquibase migrations when running in-memory
liquibase:
  enabled: true